services:
  postgres:
    image: postgres:latest
    container_name: sonarqube-postgres
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    depends_on:
      - postgres
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://postgres/sonar
      - SONAR_JDBC_USERNAME=admin
      - SONAR_JDBC_PASSWORD=admin
    restart: unless-stopped

volumes:
  postgres_data:
